package com.tflite;

import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;

/**
 * Abstract base class for the NativeRNTfliteSpec module.
 * This class is used when the Old Architecture is enabled.
 * When New Architecture is enabled, the actual spec is auto-generated by codegen.
 */
abstract class NativeRNTfliteSpec extends ReactContextBaseJavaModule {
  NativeRNTfliteSpec(ReactApplicationContext context) {
    super(context);
  }
}
